### PR TITLE
Switch from tslint to eslint

### PR DESCRIPTION
**Pull request by kzys**
First of all, thank you for making such a great extension!

This pull request adds eslint instead of tslint, as you planned in #134. It doesn't introduce any prettier configuration yet, but it should be ready for review.

### CODE REVIEW

**Comment by kzys** [comment]
Hmm, would #148 fix the tests on Windows?

**Comment by tuttieee** [comment]
Thank you for the contribution, but sorry, the test is now broken because the testing package has been changed from `vscode` to `vscode-test` but it was not successful to migrate it.
Please wait for a while.

**Comment by kzys** [comment]
Thanks for the quick reply. I'm happy to help #148 if you are not actively working on that right now.

**Comment by tuttieee** [comment]
I'm sorry, to migrate the test packages and make them work, I upgraded the entire dependencies of this package in #173 which included introducing eslint.

**Pull request closed without merging**
